In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('play_tennis Basic.csv')
data.head()
data.drop(columns=['day'], inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
# Probability of PlayTennis = Yes and No

prob_yes = 9/14
prob_no = 5/14

print("Probability of PlayTennis = Yes: ", prob_yes)
print("Probability of PlayTennis = No: ", prob_no)

Probability of PlayTennis = Yes:  0.6428571428571429
Probability of PlayTennis = No:  0.35714285714285715

In [8]:
# outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
prob_outlook_NO = 0
prob_rainy_NO = 2/5
prob_sunny_NO = 3/5

prob_outlook_YES = 4/9
prob_rainy_YES = 3/9
prob_sunny_YES = 2/9

In [11]:
# Temperature

pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
prob_cool_NO = 1/5
prob_hot_NO = 2/5
prob_mild_NO = 2/5

prob_cool_YES = 3/9
prob_hot_YES = 2/9
prob_mild_YES = 4/9

In [13]:
# Humidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
prob_high_NO = 4/5
prob_normal_NO = 1/5

prob_high_YES = 3/9
prob_normal_YES = 6/9

In [15]:
# Wind

pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [16]:
prob_Strong_NO = 3/5
prob_Weak_NO = 2/5

prob_Strong_YES = 3/9
prob_Weak_YES = 6/9

In [17]:
# Outlook = 'Sunny', Temperature = 'Cool', Humidity = 'High', Wind = 'week'

pyes = prob_yes * prob_sunny_YES * prob_cool_YES * prob_high_YES * prob_Weak_YES
pno = prob_no * prob_sunny_NO * prob_cool_NO * prob_high_NO * prob_Weak_NO

print("Probability of PlayTennis = Yes: ", pyes)
print("Probability of PlayTennis = No: ", pno)

Probability of PlayTennis = Yes:  0.010582010582010581
Probability of PlayTennis = No:  0.013714285714285715